### DISCUSSION TITLE
Getting started to publish to Play Store

### DISCUSSION THREAD

**Discussion by bpolaszek** [sparkfabrik/android-build-action#7] [Q&A] [answered]
[Newbie inside] 

Hi and thanks for your brilliant work! 👋 
We are doing our first Capacitor app, and now the time has come to publish it to the stores. 
As we are 100% newbies into iOS/Android apps releasing, but a freelance helped us publish it to the Apple App Store thanks to your other GA [IOS Build Action](https://github.com/sparkfabrik/ios-build-action).

I thought the Android one would presumably be easier, but there are some key concepts I have to understand.
Currently, I open Android Studio, _Build -> Generate Signed Bundle_, and I get an `.aab` once I chose the appropriate KeyStore, unlocked with the appropriate KeyStore password, then chose the appropriate key, unlocked with the appropriate passphrase.
Then I can upload the file manually into Google Play Console.

Now when I want to use your action in order to automate things, I can set the base64 keystore into `keystore-content`, set the keystore password into `keystore-password` and choose the appropriate key inside `keystore-alias`, but where can I set the passphrase of that key? Apart from this, could you give more info about what I'm supposed to fill into `json-key-data` / where to find that information?

On the Google Play Console side, I noticed that I can download an `App signing key certificate` and an `Upload key certificate` - am I supposed to use this somewhere I didn't figure out?

Sorry for bothering, but any help would make my day!

Thanks! 🙏 
Ben

**Comment by edodusi** [comment, marked as answer]
Hey @bpolaszek! Thank you for the compliments!
I'm aware that it can be difficult to use a product that I built for a specific project at my company and then decided to open-source, I will try to help as much as possible.

First of all, the documentation (README) should be updated and we should include instructions for the new Play Store upload feature.
The `keystore-password` is the password for both the keystore and the alias, you should set the same for both of them: I know that maybe it sounds strange but it's the config I use internally so in this Action it's the same.

The `json-key-data` is the key that you must download from Google. You have to follow this guide: https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply and then provide the JSON file to the `json-key-data` property **as a one line string** (this is important)

Here, let me show you the integration we are using in a working project, I hope it can help:
```yaml
    - uses: sparkfabrik/android-build-action@v1.2.0
        with:
          build-type: bundle
          increment-build-number: true
          gradle-task: bundleRelease
          package-name: app.bundle.id
          keystore-content: ${{ secrets.KEYSTORE_CONTENT }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.KEYSTORE_ALIAS }}
          json-key-data: ${{ secrets.PLAY_STORE_JSON_KEY_DATA }}
          upload-to-play-store: true
          project-path: android
          output-path: appName-${{ github.sha }}.aab
          browserstack-upload: false
```
