### ISSUE TITLE
Make it possible to change Java version

### ISSUE THREAD

**Issue by marie-bnl** [sparkfabrik/android-build-action#29]
Newer Android Studio (Hedgehog) projects require Java 17 to be built. There should be an option to use Java 17.

**Comment by edodusi** [comment]
@EmilianoMorghen I think we should investigate this one

**Comment by jcardus** [comment]
I'm having the same issue

**Comment by tachibana-shin** [comment]
This can be easily fixed by installing java 17 first:
```yaml

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

```
