### ISSUE TITLE
path '.' duplicate last dir

### ISSUE THREAD

**Issue by gcb** [sparkfabrik/android-build-action#31]
using `project_path: .` when gradlew is on the repo root will fail the build with

>  Couldn't find gradlew at path '/home/runner/work/repo_name/repo_name/gradlew'

```
# minimum reproducible case using job from README
jobs:
  maybe-build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: my-app.apk
          browserstack-upload: false
          ruby-version: "2.7.5"
          bundler-version: "2.3.26"
          fastlane-env: "debug"
```
